sonar.projectKey=netgrif_application-engine
sonar.organization=netgrif-oss
sonar.links.homepage=https://platform.netgrif.cloud
sonar.links.ci=https://github.com/netgrif/application-engine/actions
sonar.links.issue=https://github.com/netgrif/application-engine/issues
sonar.verbose=false

# Path to sources
sonar.sources=application-engine/src/main/java,application-engine/src/main/groovy,nae-object-library/src/main/java,nae-spring-core-adapter/src/main/java,nae-user-common/src/main/java,nae-user-ce/src/main/java
sonar.exclusions=docs,.run,.github
#sonar.inclusions=

# Path to tests
sonar.tests=application-engine/src/test/java,application-engine/src/test/groovy
#sonar.test.exclusions=
#sonar.test.inclusions=

# Source encoding
sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=
