@startuml

class Log {
    LocalDateTime created
    String message
    String thread
    Level level
}

class TaskAssignedLog extends Log {
    User delegate
    Task task
}

class TaskFinishedLog extends Log {
    User assignee
    Task task
}

enum Level {
    TRACE
    DEBUG
    INFO
    WARN
    ERROR
    FATAL
}

Log -- Level

@enduml