package com.netgrif.application.engine.menu.service;

import com.netgrif.application.engine.menu.domain.MenuItemBody;
import com.netgrif.application.engine.menu.domain.templates.*;
import com.netgrif.application.engine.menu.utils.MenuItemUtils;
import com.netgrif.application.engine.petrinet.domain.I18nString;

import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * Holder class that manages predefined menu item templates.
 * <p>
 * This class provides a central registry for menu item templates that can be used
 * throughout the application. Templates are identified by unique string identifiers
 * and can be retrieved or transformed into user-selectable options.
 * </p>
 */
public class MenuItemTemplateHolder {
    /**
     * Map of available menu item templates indexed by their unique identifiers.
     * <p>
     * Each entry maps a template identifier to its corresponding Template instance.
     * This map is immutable and initialized with predefined templates.
     * The key is the template identifier (String), and the value is the Template instance.
     * </p>
     */
    private final static Map<String, Template> templates = Map.of(
            TabbedCaseViewTemplate.IDENTIFIER, new TabbedCaseViewTemplate(),
            TabbedTaskViewTemplate.IDENTIFIER, new TabbedTaskViewTemplate(),
            SimpleCaseViewTemplate.IDENTIFIER, new SimpleCaseViewTemplate(),
            SimpleTaskViewTemplate.IDENTIFIER, new SimpleTaskViewTemplate(),
            SingleTaskViewTemplate.IDENTIFIER, new SingleTaskViewTemplate(),
            TabbedTicketViewTemplate.IDENTIFIER, new TabbedTicketViewTemplate(),
            CustomViewTemplate.IDENTIFIER, new CustomViewTemplate(),
            FolderTemplate.IDENTIFIER, new FolderTemplate()
    );


    /**
     * Retrieves a template by its unique identifier.
     * <p>
     * This method looks up and returns the Template instance associated with the
     * provided identifier from the templates registry.
     * </p>
     *
     * @param identifier the unique identifier of the template to retrieve
     * @return an Optional containing the MenuItemBody instance if found, or empty Optional if no template exists for the given identifier
     */
    public static Optional<MenuItemBody> get(String identifier) {
        return Optional.ofNullable(templates.get(identifier)).map(Template::getTemplate);
    }

    /**
     * Retrieves a template by its unique identifier and configures it with the provided URI and menu item identifier.
     * <p>
     * This method looks up the Template instance associated with the provided identifier from the templates registry,
     * and then configures the template's body with the specified URI and menu item identifier.
     * </p>
     *
     * @param identifier the unique identifier of the template to retrieve
     * @param uri the URI to set on the template's body
     * @param menuItemIdentifier the menu item identifier to set on the template's body
     * @return an Optional containing the configured MenuItemBody instance if found, or empty Optional if no template exists for the given identifier
     */
    public static Optional<MenuItemBody> get(String identifier, String uri, String menuItemIdentifier) {
        return get(identifier).map(body -> {
            body.setUri(uri);
            body.setIdentifier(menuItemIdentifier);
            return body;
        });
    }

    /**
     * Retrieves a template by its unique identifier and configures it with the provided URI and menu name.
     * <p>
     * This method looks up the Template instance associated with the provided identifier from the templates registry,
     * and then configures the template's body with the specified URI and internationalized menu name.
     * The menu item identifier is automatically generated by sanitizing the default menu name value.
     * If the default value is null or blank, the first available translation is used instead.
     * </p>
     *
     * @param identifier the unique identifier of the template to retrieve
     * @param uri the URI to set on the template's body
     * @param menuName the internationalized menu name to set on the template's body
     * @return an Optional containing the configured MenuItemBody instance if found, or empty Optional if no template exists for the given identifier
     * @throws IllegalArgumentException if the menu name has no default value or translations
     */
    public static Optional<MenuItemBody> get(String identifier, String uri, I18nString menuName) {
        return get(identifier).map(body -> {
            body.setUri(uri);
            body.setMenuName(menuName);
            String defaultName = menuName.getDefaultValue();
            if (defaultName == null || defaultName.isBlank()) {
                defaultName = menuName.getTranslations().values().stream()
                        .findAny()
                        .orElseThrow(() -> new IllegalArgumentException("Please provide a name for the menu item"));
            }
            body.setIdentifier(MenuItemUtils.sanitize(defaultName));
            return body;
        });
    }

    /**
     * Transforms the available templates into a map of selectable options.
     * <p>
     * This method converts the templates map into a format suitable for displaying
     * as user-selectable options, where the key is the template identifier and the
     * value is the internationalized name of the template.
     * </p>
     *
     * @return a map where keys are template identifiers and values are internationalized template names
     */
    public static Map<String, I18nString> transformToOptions() {
        return templates.entrySet().stream()
                .collect(Collectors.toMap(
                        Map.Entry::getKey,
                        entry -> entry.getValue().getName()
                ));
    }
}
