package com.netgrif.application.engine.objects.workspace;

// todo javadoc
public final class DefaultWorkspaceConstants {
    public static final String DEFAULT_WORKSPACE_ID = "default";
    public static final String DEFAULT_WORKSPACE_NAME = "Default";
    public static final String DEFAULT_WORKSPACE_DESC = "A default workspace generated by the system.";
}
