template header
ruleId
whenCondition
thenAction

import com.netgrif.workflow.auth.service.interfaces.IUserService;
import com.netgrif.workflow.elastic.service.interfaces.IElasticCaseService;
import com.netgrif.workflow.elastic.service.interfaces.IElasticTaskService;
import com.netgrif.workflow.mail.IMailService;
import com.netgrif.workflow.workflow.service.interfaces.IDataService;
import com.netgrif.workflow.workflow.service.interfaces.ITaskService;
import com.netgrif.workflow.workflow.service.interfaces.IWorkflowService;
import java.util.HashMap;
import java.util.ArrayList;
import org.slf4j.Logger;
import java.time.LocalDate;
import java.time.LocalDateTime;
import com.netgrif.workflow.utils.DateUtils;
import com.netgrif.workflow.rules.domain.facts.CaseEvaluation;
import java.util.concurrent.atomic.AtomicInteger

import com.netgrif.workflow.workflow.domain.*
import com.netgrif.workflow.rules.domain.facts.*
import com.netgrif.workflow.petrinet.domain.*
import com.netgrif.workflow.rules.domain.FactRepository
import com.netgrif.workflow.rules.domain.facts.TransitionEvent

global IWorkflowService workflowService;
global ITaskService taskService;
global IElasticCaseService elasticCaseService;
global IElasticTaskService elasticTaskService;
global IDataService dataService;
global IMailService mailService;
global IUserService userService;
global FactRepository factRepository;
global Logger log;

template "standard_template"

rule "@{ruleId}"
  dialect "mvel"
  when
    @{whenCondition}
  then
    @{thenAction}
end
end template