//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.02 at 10:38:56 AM CET 
//


package com.netgrif.workflow.importer.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Id_QNAME = new QName("", "id");
    private final static QName _Title_QNAME = new QName("", "title");
    private final static QName _Placeholder_QNAME = new QName("", "placeholder");
    private final static QName _Desc_QNAME = new QName("", "desc");
    private final static QName _Values_QNAME = new QName("", "values");
    private final static QName _Valid_QNAME = new QName("", "valid");
    private final static QName _Init_QNAME = new QName("", "init");
    private final static QName _Encryption_QNAME = new QName("", "encryption");
    private final static QName _Action_QNAME = new QName("", "action");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _TransitionRef_QNAME = new QName("", "transitionRef");
    private final static QName _Perform_QNAME = new QName("", "perform");
    private final static QName _Delegate_QNAME = new QName("", "delegate");
    private final static QName _Behavior_QNAME = new QName("", "behavior");
    private final static QName _X_QNAME = new QName("", "x");
    private final static QName _Y_QNAME = new QName("", "y");
    private final static QName _Label_QNAME = new QName("", "label");
    private final static QName _Icon_QNAME = new QName("", "icon");
    private final static QName _Priority_QNAME = new QName("", "priority");
    private final static QName _Alignment_QNAME = new QName("", "alignment");
    private final static QName _Stretch_QNAME = new QName("", "stretch");
    private final static QName _Tokens_QNAME = new QName("", "tokens");
    private final static QName _IsStatic_QNAME = new QName("", "isStatic");
    private final static QName _Static_QNAME = new QName("", "static");
    private final static QName _SourceId_QNAME = new QName("", "sourceId");
    private final static QName _DestinationId_QNAME = new QName("", "destinationId");
    private final static QName _Multiplicity_QNAME = new QName("", "multiplicity");
    private final static QName _Type_QNAME = new QName("", "type");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link EncryptionType }
     * 
     */
    public EncryptionType createEncryptionType() {
        return new EncryptionType();
    }

    /**
     * Create an instance of {@link ActionType }
     * 
     */
    public ActionType createActionType() {
        return new ActionType();
    }

    /**
     * Create an instance of {@link DocumentRef }
     * 
     */
    public DocumentRef createDocumentRef() {
        return new DocumentRef();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Mapping }
     * 
     */
    public Mapping createMapping() {
        return new Mapping();
    }

    /**
     * Create an instance of {@link RoleRef }
     * 
     */
    public RoleRef createRoleRef() {
        return new RoleRef();
    }

    /**
     * Create an instance of {@link Logic }
     * 
     */
    public Logic createLogic() {
        return new Logic();
    }

    /**
     * Create an instance of {@link DataRef }
     * 
     */
    public DataRef createDataRef() {
        return new DataRef();
    }

    /**
     * Create an instance of {@link Transition }
     * 
     */
    public Transition createTransition() {
        return new Transition();
    }

    /**
     * Create an instance of {@link Trigger }
     * 
     */
    public Trigger createTrigger() {
        return new Trigger();
    }

    /**
     * Create an instance of {@link TransactionRef }
     * 
     */
    public TransactionRef createTransactionRef() {
        return new TransactionRef();
    }

    /**
     * Create an instance of {@link DataGroup }
     * 
     */
    public DataGroup createDataGroup() {
        return new DataGroup();
    }

    /**
     * Create an instance of {@link Place }
     * 
     */
    public Place createPlace() {
        return new Place();
    }

    /**
     * Create an instance of {@link Arc }
     * 
     */
    public Arc createArc() {
        return new Arc();
    }

    /**
     * Create an instance of {@link BreakPoint }
     * 
     */
    public BreakPoint createBreakPoint() {
        return new BreakPoint();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id")
    public JAXBElement<Long> createId(Long value) {
        return new JAXBElement<Long>(_Id_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "placeholder")
    public JAXBElement<String> createPlaceholder(String value) {
        return new JAXBElement<String>(_Placeholder_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "desc")
    public JAXBElement<String> createDesc(String value) {
        return new JAXBElement<String>(_Desc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "values")
    public JAXBElement<String> createValues(String value) {
        return new JAXBElement<String>(_Values_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "valid")
    public JAXBElement<String> createValid(String value) {
        return new JAXBElement<String>(_Valid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "init")
    public JAXBElement<String> createInit(String value) {
        return new JAXBElement<String>(_Init_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncryptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "encryption")
    public JAXBElement<EncryptionType> createEncryption(EncryptionType value) {
        return new JAXBElement<EncryptionType>(_Encryption_QNAME, EncryptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "action")
    public JAXBElement<ActionType> createAction(ActionType value) {
        return new JAXBElement<ActionType>(_Action_QNAME, ActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "transitionRef")
    public JAXBElement<Byte> createTransitionRef(Byte value) {
        return new JAXBElement<Byte>(_TransitionRef_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "perform")
    public JAXBElement<Boolean> createPerform(Boolean value) {
        return new JAXBElement<Boolean>(_Perform_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "delegate")
    public JAXBElement<Boolean> createDelegate(Boolean value) {
        return new JAXBElement<Boolean>(_Delegate_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "behavior")
    public JAXBElement<String> createBehavior(String value) {
        return new JAXBElement<String>(_Behavior_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "x")
    public JAXBElement<Short> createX(Short value) {
        return new JAXBElement<Short>(_X_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "y")
    public JAXBElement<Short> createY(Short value) {
        return new JAXBElement<Short>(_Y_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "label")
    public JAXBElement<String> createLabel(String value) {
        return new JAXBElement<String>(_Label_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "icon")
    public JAXBElement<String> createIcon(String value) {
        return new JAXBElement<String>(_Icon_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "priority")
    public JAXBElement<Integer> createPriority(Integer value) {
        return new JAXBElement<Integer>(_Priority_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataGroupAlignment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "alignment")
    public JAXBElement<DataGroupAlignment> createAlignment(DataGroupAlignment value) {
        return new JAXBElement<DataGroupAlignment>(_Alignment_QNAME, DataGroupAlignment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stretch")
    public JAXBElement<Boolean> createStretch(Boolean value) {
        return new JAXBElement<Boolean>(_Stretch_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tokens")
    public JAXBElement<Integer> createTokens(Integer value) {
        return new JAXBElement<Integer>(_Tokens_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "isStatic")
    public JAXBElement<Boolean> createIsStatic(Boolean value) {
        return new JAXBElement<Boolean>(_IsStatic_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "static")
    public JAXBElement<Boolean> createStatic(Boolean value) {
        return new JAXBElement<Boolean>(_Static_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sourceId")
    public JAXBElement<Long> createSourceId(Long value) {
        return new JAXBElement<Long>(_SourceId_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "destinationId")
    public JAXBElement<Long> createDestinationId(Long value) {
        return new JAXBElement<Long>(_DestinationId_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "multiplicity")
    public JAXBElement<Integer> createMultiplicity(Integer value) {
        return new JAXBElement<Integer>(_Multiplicity_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

}
